# Generated by Django 4.0.3 on 2022-05-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(choices=[('d', 'draft'), ('p', 'published'), ('i', 'investigate'), ('r', 'reject')], max_length=1),
        ),
    ]
